import type { Destination } from '@javits/domain';

/**
 * Seed destinations. Positions are in meters in each floor's local frame.
 * Layout is chosen so the mock router produces interesting routes with real
 * turns, floor changes, and multi-building traversal.
 */
export const seedDestinations: Destination[] = [
  // ---------- North Building · Level 1 ----------
  {
    id: 'dest_north_entrance',
    venueId: 'venue_javits',
    buildingId: 'bldg_north',
    floorId: 'floor_north_l1',
    name: 'North Entrance',
    category: 'entrance',
    tags: ['entrance', 'north'],
    position: { buildingId: 'bldg_north', floorId: 'floor_north_l1', x: -100, y: 0 },
    isFeatured: false,
  },
  {
    id: 'dest_registration',
    venueId: 'venue_javits',
    buildingId: 'bldg_north',
    floorId: 'floor_north_l1',
    zoneId: 'zone_n_lobby',
    name: 'Registration',
    category: 'registration',
    tags: ['badge', 'check-in'],
    description: 'Pick up your badge here. Fast lane for pre-registered attendees.',
    position: { buildingId: 'bldg_north', floorId: 'floor_north_l1', x: -40, y: -40 },
    isFeatured: true,
    iconKey: 'registration',
  },
  {
    id: 'dest_help_desk_n',
    venueId: 'venue_javits',
    buildingId: 'bldg_north',
    floorId: 'floor_north_l1',
    zoneId: 'zone_n_lobby',
    name: 'Help Desk — North',
    category: 'help_desk',
    tags: ['info', 'help'],
    position: { buildingId: 'bldg_north', floorId: 'floor_north_l1', x: -40, y: 40 },
    isFeatured: true,
  },
  {
    id: 'dest_cafe_42',
    venueId: 'venue_javits',
    buildingId: 'bldg_north',
    floorId: 'floor_north_l1',
    name: 'Café 42',
    category: 'coffee',
    tags: ['coffee', 'snack'],
    description: 'Specialty coffee and pastries.',
    position: { buildingId: 'bldg_north', floorId: 'floor_north_l1', x: 0, y: -20 },
    isFeatured: false,
  },
  {
    id: 'dest_restroom_n_l1',
    venueId: 'venue_javits',
    buildingId: 'bldg_north',
    floorId: 'floor_north_l1',
    name: 'Restrooms — North L1',
    category: 'restroom',
    tags: ['bathroom', 'wc'],
    position: { buildingId: 'bldg_north', floorId: 'floor_north_l1', x: 20, y: 30 },
    isFeatured: false,
  },
  {
    id: 'dest_hall_a',
    venueId: 'venue_javits',
    buildingId: 'bldg_north',
    floorId: 'floor_north_l1',
    zoneId: 'zone_hall_a',
    name: 'Hall A',
    category: 'hall',
    tags: ['exhibition', 'keynote'],
    description: 'Main exhibition hall — 240 booths.',
    position: { buildingId: 'bldg_north', floorId: 'floor_north_l1', x: 60, y: -40 },
    isFeatured: true,
    displayCode: 'A',
  },
  {
    id: 'dest_hall_b',
    venueId: 'venue_javits',
    buildingId: 'bldg_north',
    floorId: 'floor_north_l1',
    zoneId: 'zone_hall_b',
    name: 'Hall B',
    category: 'hall',
    tags: ['exhibition'],
    position: { buildingId: 'bldg_north', floorId: 'floor_north_l1', x: 60, y: 40 },
    isFeatured: false,
    displayCode: 'B',
  },
  {
    id: 'dest_elev_n_l1',
    venueId: 'venue_javits',
    buildingId: 'bldg_north',
    floorId: 'floor_north_l1',
    name: 'Elevator — North Core',
    category: 'elevator',
    tags: ['accessible', 'lift'],
    position: { buildingId: 'bldg_north', floorId: 'floor_north_l1', x: 50, y: 0 },
    isFeatured: false,
  },
  {
    id: 'dest_exit_n',
    venueId: 'venue_javits',
    buildingId: 'bldg_north',
    floorId: 'floor_north_l1',
    name: 'Emergency Exit — North',
    category: 'exit',
    tags: ['exit', 'emergency'],
    position: { buildingId: 'bldg_north', floorId: 'floor_north_l1', x: 100, y: -75 },
    isFeatured: false,
  },

  // ---------- North Building · Level 2 ----------
  {
    id: 'dest_starbucks',
    venueId: 'venue_javits',
    buildingId: 'bldg_north',
    floorId: 'floor_north_l2',
    zoneId: 'zone_l2_food',
    name: 'Starbucks',
    category: 'coffee',
    tags: ['coffee'],
    position: { buildingId: 'bldg_north', floorId: 'floor_north_l2', x: -30, y: -40 },
    isFeatured: false,
  },
  {
    id: 'dest_food_court',
    venueId: 'venue_javits',
    buildingId: 'bldg_north',
    floorId: 'floor_north_l2',
    zoneId: 'zone_l2_food',
    name: 'Food Court',
    category: 'food',
    tags: ['lunch', 'food'],
    description: 'Rotating vendors: sandwiches, bowls, salads, halal carts.',
    position: { buildingId: 'bldg_north', floorId: 'floor_north_l2', x: 0, y: -20 },
    isFeatured: true,
  },
  {
    id: 'dest_lounge',
    venueId: 'venue_javits',
    buildingId: 'bldg_north',
    floorId: 'floor_north_l2',
    zoneId: 'zone_l2_lounge',
    name: 'Exhibitor Lounge',
    category: 'other',
    tags: ['quiet', 'workspace'],
    position: { buildingId: 'bldg_north', floorId: 'floor_north_l2', x: 30, y: 40 },
    isFeatured: false,
  },
  {
    id: 'dest_restroom_n_l2',
    venueId: 'venue_javits',
    buildingId: 'bldg_north',
    floorId: 'floor_north_l2',
    name: 'Restrooms — North L2',
    category: 'restroom',
    tags: ['wc'],
    position: { buildingId: 'bldg_north', floorId: 'floor_north_l2', x: 20, y: 30 },
    isFeatured: false,
  },

  // ---------- North Building · Level 4 ----------
  {
    id: 'dest_room_402',
    venueId: 'venue_javits',
    buildingId: 'bldg_north',
    floorId: 'floor_north_l4',
    name: 'Room 402',
    category: 'meeting_room',
    tags: ['workshop', 'session'],
    description: 'Workshop room · capacity 60.',
    position: { buildingId: 'bldg_north', floorId: 'floor_north_l4', x: -40, y: 30 },
    isFeatured: true,
    displayCode: '402',
  },
  {
    id: 'dest_room_411',
    venueId: 'venue_javits',
    buildingId: 'bldg_north',
    floorId: 'floor_north_l4',
    name: 'Room 411',
    category: 'meeting_room',
    tags: ['session'],
    position: { buildingId: 'bldg_north', floorId: 'floor_north_l4', x: 40, y: 30 },
    isFeatured: false,
    displayCode: '411',
  },
  {
    id: 'dest_room_415',
    venueId: 'venue_javits',
    buildingId: 'bldg_north',
    floorId: 'floor_north_l4',
    name: 'Room 415',
    category: 'meeting_room',
    tags: ['session'],
    position: { buildingId: 'bldg_north', floorId: 'floor_north_l4', x: 80, y: -30 },
    isFeatured: false,
    displayCode: '415',
  },

  // ---------- South Building · Level 1 ----------
  {
    id: 'dest_south_entrance',
    venueId: 'venue_javits',
    buildingId: 'bldg_south',
    floorId: 'floor_south_l1',
    name: 'South Entrance',
    category: 'entrance',
    tags: ['entrance', 'south'],
    position: { buildingId: 'bldg_south', floorId: 'floor_south_l1', x: -100, y: 0 },
    isFeatured: false,
  },
  {
    id: 'dest_hall_s',
    venueId: 'venue_javits',
    buildingId: 'bldg_south',
    floorId: 'floor_south_l1',
    zoneId: 'zone_hall_s',
    name: 'South Hall',
    category: 'hall',
    tags: ['exhibition'],
    position: { buildingId: 'bldg_south', floorId: 'floor_south_l1', x: 40, y: 0 },
    isFeatured: true,
    displayCode: 'S',
  },
  {
    id: 'dest_restroom_s_l1',
    venueId: 'venue_javits',
    buildingId: 'bldg_south',
    floorId: 'floor_south_l1',
    name: 'Restrooms — South L1',
    category: 'restroom',
    tags: ['wc'],
    position: { buildingId: 'bldg_south', floorId: 'floor_south_l1', x: 20, y: 40 },
    isFeatured: false,
  },
  {
    id: 'dest_booth_4512',
    venueId: 'venue_javits',
    buildingId: 'bldg_south',
    floorId: 'floor_south_l1',
    zoneId: 'zone_hall_s',
    name: 'Booth 4512 — Acme Robotics',
    category: 'exhibitor_booth',
    tags: ['robotics', 'automation'],
    position: { buildingId: 'bldg_south', floorId: 'floor_south_l1', x: 70, y: -20 },
    isFeatured: true,
    displayCode: '4512',
    exhibitorId: 'ex_acme',
  },
  {
    id: 'dest_booth_3481',
    venueId: 'venue_javits',
    buildingId: 'bldg_north',
    floorId: 'floor_north_l1',
    zoneId: 'zone_hall_a',
    name: 'Booth 3481 — Globex Cloud',
    category: 'exhibitor_booth',
    tags: ['cloud', 'software'],
    position: { buildingId: 'bldg_north', floorId: 'floor_north_l1', x: 80, y: -60 },
    isFeatured: false,
    displayCode: '3481',
    exhibitorId: 'ex_globex',
  },

  // ---------- South Building · Level 2 ----------
  {
    id: 'dest_press_center',
    venueId: 'venue_javits',
    buildingId: 'bldg_south',
    floorId: 'floor_south_l2',
    zoneId: 'zone_l2_press',
    name: 'Press Center',
    category: 'help_desk',
    tags: ['press', 'media'],
    position: { buildingId: 'bldg_south', floorId: 'floor_south_l2', x: 0, y: 0 },
    isFeatured: false,
  },
];
