import type { Destination } from '@javits/domain';

/**
 * Seed destinations — SAMPLE DATA modeled on the Javits Center design brief.
 * Positions are meters in each floor's local frame, laid out so the mock
 * router produces believable multi-floor and cross-building routes.
 *
 * Staff-gated destinations carry the `staff-gated` tag; the public prototype
 * surfaces them in search but a future Staff Mode gates navigation to them.
 */
export const seedDestinations: Destination[] = [
  // ---------- Main Building · Level 1 ----------
  {
    id: 'dest_crystal_palace_entrance',
    venueId: 'venue_javits',
    buildingId: 'bldg_main',
    floorId: 'floor_main_l1',
    zoneId: 'zone_crystal_palace',
    name: 'Crystal Palace Entrance',
    category: 'entrance',
    tags: ['entrance', 'main entrance', '11th avenue'],
    description: 'Main entrance on 11th Avenue. Glass atrium lobby.',
    position: { buildingId: 'bldg_main', floorId: 'floor_main_l1', x: -100, y: 0 },
    isFeatured: false,
  },
  {
    id: 'dest_registration',
    venueId: 'venue_javits',
    buildingId: 'bldg_main',
    floorId: 'floor_main_l1',
    zoneId: 'zone_l1_registration',
    name: 'Level 1 Registration',
    category: 'registration',
    tags: ['badge', 'check-in', 'registration'],
    description: 'Badge pickup and check-in. Fast lane for pre-registered attendees. (Sample data)',
    position: { buildingId: 'bldg_main', floorId: 'floor_main_l1', x: -40, y: -40 },
    isFeatured: true,
    iconKey: 'registration',
  },
  {
    id: 'dest_coat_check',
    venueId: 'venue_javits',
    buildingId: 'bldg_main',
    floorId: 'floor_main_l1',
    zoneId: 'zone_crystal_palace',
    name: 'Coat Check',
    category: 'coat_check',
    tags: ['coat', 'luggage', 'storage'],
    position: { buildingId: 'bldg_main', floorId: 'floor_main_l1', x: -40, y: 40 },
    isFeatured: false,
  },
  {
    id: 'dest_accessibility_services',
    venueId: 'venue_javits',
    buildingId: 'bldg_main',
    floorId: 'floor_main_l1',
    zoneId: 'zone_crystal_palace',
    name: 'Accessibility Services',
    category: 'info',
    tags: ['accessibility', 'wheelchair', 'assistance', 'ada'],
    description: 'Wheelchair loans, accessible-route guidance, and assistance requests.',
    position: { buildingId: 'bldg_main', floorId: 'floor_main_l1', x: -20, y: 40 },
    isFeatured: true,
  },
  {
    id: 'dest_restroom_main_l1',
    venueId: 'venue_javits',
    buildingId: 'bldg_main',
    floorId: 'floor_main_l1',
    name: 'Restrooms — Level 1',
    category: 'restroom',
    tags: ['bathroom', 'wc', 'accessible'],
    position: { buildingId: 'bldg_main', floorId: 'floor_main_l1', x: 20, y: 30 },
    isFeatured: false,
  },
  {
    id: 'dest_escalator_main',
    venueId: 'venue_javits',
    buildingId: 'bldg_main',
    floorId: 'floor_main_l1',
    name: 'Escalators — Crystal Palace',
    category: 'escalator',
    tags: ['escalator'],
    position: { buildingId: 'bldg_main', floorId: 'floor_main_l1', x: -20, y: 0 },
    isFeatured: false,
  },
  {
    id: 'dest_elevator_main',
    venueId: 'venue_javits',
    buildingId: 'bldg_main',
    floorId: 'floor_main_l1',
    name: 'Elevator Bank — Main',
    category: 'elevator',
    tags: ['elevator', 'accessible', 'lift'],
    position: { buildingId: 'bldg_main', floorId: 'floor_main_l1', x: 50, y: 0 },
    isFeatured: false,
  },
  {
    id: 'dest_taxi_stand',
    venueId: 'venue_javits',
    buildingId: 'bldg_main',
    floorId: 'floor_main_l1',
    zoneId: 'zone_l1_transport',
    name: 'Taxi Stand',
    category: 'exit',
    tags: ['taxi', 'transportation', 'ground transport'],
    description: 'Taxi queue outside the 11th Avenue entrance.',
    position: { buildingId: 'bldg_main', floorId: 'floor_main_l1', x: -105, y: -30 },
    isFeatured: false,
  },
  {
    id: 'dest_rideshare_pickup',
    venueId: 'venue_javits',
    buildingId: 'bldg_main',
    floorId: 'floor_main_l1',
    zoneId: 'zone_l1_transport',
    name: 'Rideshare Pickup',
    category: 'exit',
    tags: ['rideshare', 'uber', 'lyft', 'transportation'],
    description: 'Designated rideshare pickup zone, west side.',
    position: { buildingId: 'bldg_main', floorId: 'floor_main_l1', x: -105, y: 30 },
    isFeatured: false,
  },
  {
    id: 'dest_subway_hudson_yards',
    venueId: 'venue_javits',
    buildingId: 'bldg_main',
    floorId: 'floor_main_l1',
    zoneId: 'zone_l1_transport',
    name: 'Subway — 34 St-Hudson Yards',
    category: 'exit',
    tags: ['subway', '7 train', 'transportation', 'transit'],
    description: '7 train at 34 St-Hudson Yards, one block east.',
    position: { buildingId: 'bldg_main', floorId: 'floor_main_l1', x: -115, y: 0 },
    isFeatured: false,
  },

  // ---------- Main Building · Level 3 ----------
  {
    id: 'dest_hall_3a',
    venueId: 'venue_javits',
    buildingId: 'bldg_main',
    floorId: 'floor_main_l3',
    zoneId: 'zone_hall_3a',
    name: 'Hall 3A',
    category: 'hall',
    tags: ['exhibition', 'expo floor', 'keynote'],
    description: 'Main exhibition hall — 350 booths. (Sample data)',
    position: { buildingId: 'bldg_main', floorId: 'floor_main_l3', x: 60, y: -40 },
    isFeatured: true,
    displayCode: '3A',
  },
  {
    id: 'dest_hall_3b',
    venueId: 'venue_javits',
    buildingId: 'bldg_main',
    floorId: 'floor_main_l3',
    zoneId: 'zone_hall_3b',
    name: 'Hall 3B',
    category: 'hall',
    tags: ['exhibition', 'expo floor'],
    position: { buildingId: 'bldg_main', floorId: 'floor_main_l3', x: 60, y: 40 },
    isFeatured: false,
    displayCode: '3B',
  },
  {
    id: 'dest_food_court',
    venueId: 'venue_javits',
    buildingId: 'bldg_main',
    floorId: 'floor_main_l3',
    name: 'Food Court',
    category: 'food',
    tags: ['lunch', 'food', 'coffee', 'snacks'],
    description: 'Rotating vendors: sandwiches, bowls, salads, halal carts. (Sample data)',
    position: { buildingId: 'bldg_main', floorId: 'floor_main_l3', x: 0, y: -30 },
    isFeatured: true,
  },
  {
    id: 'dest_restroom_main_l3',
    venueId: 'venue_javits',
    buildingId: 'bldg_main',
    floorId: 'floor_main_l3',
    name: 'Restrooms — Level 3',
    category: 'restroom',
    tags: ['bathroom', 'wc', 'accessible'],
    position: { buildingId: 'bldg_main', floorId: 'floor_main_l3', x: 20, y: 30 },
    isFeatured: false,
  },
  {
    id: 'dest_exhibitor_service_desk',
    venueId: 'venue_javits',
    buildingId: 'bldg_main',
    floorId: 'floor_main_l3',
    zoneId: 'zone_l3_services',
    name: 'Exhibitor Service Desk',
    category: 'help_desk',
    tags: ['exhibitor', 'services', 'electrical', 'plumbing', 'av'],
    description: 'Booth services: electrical, plumbing, AV, furniture, labor. (Sample data)',
    position: { buildingId: 'bldg_main', floorId: 'floor_main_l3', x: -40, y: 30 },
    isFeatured: false,
  },
  {
    id: 'dest_tech_solutions_desk',
    venueId: 'venue_javits',
    buildingId: 'bldg_main',
    floorId: 'floor_main_l3',
    zoneId: 'zone_l3_services',
    name: 'Technology Solutions Service Desk',
    category: 'help_desk',
    tags: ['internet', 'wifi', 'network', 'exhibitor', 'support'],
    description: 'Internet, Wi-Fi, and network support for exhibitors. Hours 7 AM–6 PM during move-in. (Sample data)',
    position: { buildingId: 'bldg_main', floorId: 'floor_main_l3', x: -40, y: -30 },
    isFeatured: false,
  },
  {
    id: 'dest_booth_1845',
    venueId: 'venue_javits',
    buildingId: 'bldg_main',
    floorId: 'floor_main_l3',
    zoneId: 'zone_hall_3a',
    name: 'Booth 1845 — Acme Robotics',
    category: 'exhibitor_booth',
    tags: ['robotics', 'automation'],
    position: { buildingId: 'bldg_main', floorId: 'floor_main_l3', x: 80, y: -60 },
    isFeatured: true,
    displayCode: '1845',
    exhibitorId: 'ex_acme',
  },
  {
    id: 'dest_booth_3481',
    venueId: 'venue_javits',
    buildingId: 'bldg_main',
    floorId: 'floor_main_l3',
    zoneId: 'zone_hall_3b',
    name: 'Booth 3481 — Globex Cloud',
    category: 'exhibitor_booth',
    tags: ['cloud', 'software'],
    position: { buildingId: 'bldg_main', floorId: 'floor_main_l3', x: 80, y: 60 },
    isFeatured: false,
    displayCode: '3481',
    exhibitorId: 'ex_globex',
  },

  // ---------- Main Building · Level 4 ----------
  {
    id: 'dest_river_pavilion',
    venueId: 'venue_javits',
    buildingId: 'bldg_main',
    floorId: 'floor_main_l4',
    zoneId: 'zone_river_pavilion',
    name: 'River Pavilion',
    category: 'hall',
    tags: ['events', 'reception', 'hudson river'],
    description: 'Glass-walled event space overlooking the Hudson River.',
    position: { buildingId: 'bldg_main', floorId: 'floor_main_l4', x: 60, y: -40 },
    isFeatured: true,
  },
  {
    id: 'dest_special_events_hall',
    venueId: 'venue_javits',
    buildingId: 'bldg_main',
    floorId: 'floor_main_l4',
    zoneId: 'zone_river_pavilion',
    name: 'Special Events Hall',
    category: 'hall',
    tags: ['events', 'ceremony'],
    position: { buildingId: 'bldg_main', floorId: 'floor_main_l4', x: -40, y: -40 },
    isFeatured: false,
  },
  {
    id: 'dest_room_409',
    venueId: 'venue_javits',
    buildingId: 'bldg_main',
    floorId: 'floor_main_l4',
    zoneId: 'zone_l4_meetings',
    name: 'Room 409',
    category: 'meeting_room',
    tags: ['workshop', 'session', 'meeting'],
    description: 'Meeting room · capacity 60. (Sample data)',
    position: { buildingId: 'bldg_main', floorId: 'floor_main_l4', x: -40, y: 30 },
    isFeatured: true,
    displayCode: '409',
  },

  // ---------- Javits North · Level 1 (staff-gated) ----------
  {
    id: 'dest_loading_dock',
    venueId: 'venue_javits',
    buildingId: 'bldg_north',
    floorId: 'floor_north_l1',
    zoneId: 'zone_n_ops',
    name: 'Loading Dock',
    category: 'other',
    tags: ['staff-gated', 'freight', 'move-in', 'operations'],
    description: 'Freight and move-in access. Staff and credentialed exhibitors only.',
    position: { buildingId: 'bldg_north', floorId: 'floor_north_l1', x: 0, y: -40 },
    isFeatured: false,
  },
  {
    id: 'dest_command_center',
    venueId: 'venue_javits',
    buildingId: 'bldg_north',
    floorId: 'floor_north_l1',
    zoneId: 'zone_n_ops',
    name: 'Command Center',
    category: 'other',
    tags: ['staff-gated', 'operations', 'security'],
    description: 'Venue operations command. Staff only.',
    position: { buildingId: 'bldg_north', floorId: 'floor_north_l1', x: 0, y: 40 },
    isFeatured: false,
  },
];
